# Generated by Django 5.0.7 on 2024-09-14 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_start', models.DateField()),
                ('event_end', models.DateField()),
                ('event_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField(default=0)),
                ('nagar', models.CharField(blank=True, choices=[('100', 'aravinda nagar'), ('200', 'aishwaryam garden'), ('300', 'indra nagar'), ('400', 'other')], default='', help_text='Nagar', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SponsoredBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.events')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sponsors')),
            ],
        ),
    ]
