# Generated by Django 5.0.7 on 2026-08-21 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_japamcompletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(db_index=True, max_length=64)),
                ('playlist_label', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
