# Generated by Django 5.0.7 on 2026-08-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_playlistplay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaylistPlay',
        ),
    ]
