# Generated by Django 5.0.7 on 2026-08-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_playlistplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='japamcompletion',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
