# Generated by Django 5.0.7 on 2026-08-21 11:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_japamcompletion_duration_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Walker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('age', models.PositiveSmallIntegerField()),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Most recently logged weight, kg', max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='japamcompletion',
            name='chant_type',
            field=models.CharField(choices=[('21', '21 Gayathri Japam'), ('108', '108 Gayathri Japam'), ('om', 'Om Japam'), ('shivaya', 'Om Namah Shivaya Japam')], default='21', max_length=20),
        ),
        migrations.CreateModel(
            name='WalkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('calories_burnt', models.DecimalField(decimal_places=2, max_digits=7)),
                ('walker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_logs', to='app.walker')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
