# Generated by Django 5.0.7 on 2026-08-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_walker_alter_japamcompletion_chant_type_walklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveJapamState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='completed', max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
