# Generated by Django 5.0.7 on 2026-08-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_activejapamstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyJapamSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('total_duration_seconds', models.BigIntegerField(default=0)),
                ('chant_breakdown', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='japamcompletion',
            index=models.Index(fields=['chant_type', 'created_at'], name='app_japamco_chant_t_d9c4fb_idx'),
        ),
    ]
