# Generated by Django 5.0.7 on 2026-08-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_dailyjapamsummary_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SponsoredBy',
        ),
        migrations.DeleteModel(
            name='Sponsors',
        ),
    ]
