# Generated by Django 5.0.7 on 2026-09-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_sponsoredby_delete_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='activejapamstate',
            name='audio_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='activejapamstate',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
