from django.contrib import admin
from django.urls import path

from . import views
from .views import update_japam_state
from app.views import run_archive_cron

urlpatterns = [
    path(r'', views.home, name='nagarhome'),
    path(r'sides-sample/', views.sides_sample, name='sides_sample'),
    path(r'aug15/', views.aug15, name='aug15'),
    path(r'iday/2025/', views.iday_2025, name='iday_2025'),
    path(r'chaturthi/', views.chaturthi, name='chaturthi'),
    path(r'iday/', views.idayhome, name='idayhome'),
    path(r'wayand/', views.reliefhome, name='reliefhome'),
    path(r'collective-prayer/', views.collective_prayer, name='collective_prayer'),
    path(r'collective-prayer/japam/record/', views.record_japam_completion, name='record_japam_completion'),
    path(r'walking-log/', views.walking_log, name='walking_log'),
    path(r'walking-log/typeahead/', views.walking_log_typeahead, name='walking_log_typeahead'),
    path(r'walking-log/record/', views.record_walk_log, name='record_walk_log'),
    path(r'walking-log/data/', views.walking_log_data, name='walking_log_data'),
    path(r'traffic-signals/', views.traffic_signals, name='traffic_signals'),
    path("api/japam-state/", update_japam_state, name="japam_state_api"),
    path("api/cron/archive-japams/", run_archive_cron, name="run_archive_cron"),
    path(r'short-stories/', views.short_stories, name='short_stories'),
    path(r'short-stories/ganesha-muruga/', views.ganesha_muruga_story, name='ganesha_muruga_story'),
    path(r'short-stories/shiva-neelakantha/', views.shiva_neelakantha_story, name='shiva_neelakantha_story'),
    path(r'short-stories/muruga-soorasamharam/', views.muruga_soorasamharam_story, name='muruga_soorasamharam_story'),
    path(r'short-stories/gayatri-devi/', views.gayatri_devi_story, name='gayatri_devi_story'),
    path(r'short-stories/hanuman-sanjeevani/', views.hanuman_sanjeevani_story, name='hanuman_sanjeevani_story'),
    path(r'short-stories/jesus-calms-storm/', views.jesus_calms_storm_story, name='jesus_calms_storm_story'),
    path(r'short-stories/yunus-whale/', views.yunus_whale_story, name='yunus_whale_story'),
    path(r'timer/', views.timer_app, name='timer_app'),
    path(r'astrology/', views.astrology_home, name='astrology_home'),
    path(r'astrology/mesham/', views.astrology_mesham, name='astrology_mesham'),
    path(r'astrology/rishabam/', views.astrology_rishabam, name='astrology_rishabam'),
    path(r'astrology/mithunam/', views.astrology_mithunam, name='astrology_mithunam'),
    path(r'astrology/kadagam/', views.astrology_kadagam, name='astrology_kadagam'),
    path(r'astrology/simmam/', views.astrology_simmam, name='astrology_simmam'),
    path(r'astrology/kanni/', views.astrology_kanni, name='astrology_kanni'),
    path(r'astrology/thulam/', views.astrology_thulam, name='astrology_thulam'),
    path(r'astrology/viruchigam/', views.astrology_viruchigam, name='astrology_viruchigam'),
    path(r'astrology/dhanusu/', views.astrology_dhanusu, name='astrology_dhanusu'),
    path(r'astrology/magaram/', views.astrology_magaram, name='astrology_magaram'),
    path(r'astrology/kumbam/', views.astrology_kumbam, name='astrology_kumbam'),
    path(r'astrology/meenam/', views.astrology_meenam, name='astrology_meenam'),
    path(r'javascript-games/', views.javascript_games, name='js_games'),
    path(r'javascript-games/emoji-mask-memory/', views.emoji_mask_memory_game, name='emoji_mask_memory_game'),
    path(r'javascript-games/tic-tac-toe/', views.tic_tac_toe_game, name='tic_tac_toe_game'),
]
